[tool.jupytext]
formats = "ipynb,py:light"
cell_metadata_filter = "-all"
notebook_metadata_filter = "-all"

[tool.nbqa.addopts]
flake8 = ["--ignore=E501,E712,W291,F632,E203,F821,F403,W391,F401", "--exclude=.*,__init__.py"]
pylint = ["--ignore=no_check*,__init__.py", "--max-line-length=90", "--const-naming-style=any", "--disable=E0401,W0104,R0903,R1721,E1101,E0611,F0002,C0305,C0303,E2515"]
mypy = ["--ignore-missing-imports", "--non-interactive", "--install-types"]
